### ISSUE TITLE
Is Truecrypt Audited Yet?

### ISSUE THREAD

**Issue by DrWhax** [DrWhax/truecrypt-archive#6]
http://istruecryptauditedyet.com/

NO. Help out!

**Comment by stefansundin** [comment]
They should give this project a bigger plug. Can anyone try to ping them about it?

Out project makes their project possible. Collecting all these files makes it possible to audit TrueCrypt, so all the new attention this new project brings, they should help us fulfill our project.

**Comment by DrWhax** [comment]
I think a bunch of people has visited this page but not yet contributed. It's up to _someone_ to claim the bounty and delivering some audit.

**Comment by stefansundin** [comment]
What I meant was that their link to our project, this Github repo, should be bigger. The attention their project gets can help our project, and should.

**Comment by DrWhax** [comment]
I hope so too! I'll email Matthew.

**Comment by dy-dx** [comment]
http://istruecryptauditedyet.com/ now says Yes!

**Comment by DrWhax** [comment]
Indeed so. Closing.
