### ISSUE TITLE
Prompt users to download TrueCrypt public keys from key servers?

### ISSUE THREAD

**Issue by f3ndot** [DrWhax/truecrypt-archive#9]
It's nice that there are `.sig`s and the public keys used to sign them in the repository, but wouldn't it be best to point users to download the keys from https://pgp.mit.edu or another key server?

That way they can visually see the WoT and independently verify that the bundled public keys and signatures are not falsified. I mean, you'd have to be an idiot to fall for fake sigs due to the nature of timestamps and IDs, but it's probably good practise to enforce for a user's sake.

Dunno. Just my two cents.

**Comment by stefansundin** [comment]
Good point, I'll add it. Thanks!
